### PR TITLE
Fix notifications management

### LINKED ISSUE #69: Remove Survey Link & fix multiple notices appearing at once
As discussed, we will pause the Typeform survey for now, and re-evaluate after a year, so we need to remove the banner altogether from the dashboard. 

**Edit by Hardeep:** Please also refer to the issue mentioned in the [first comment](https://github.com/Codeinwp/neve-fse/issues/69#issuecomment-1687692898), which happens if you have a theme installed for a while (you can change the option to set the install time to a past date)

We can make sure:

- The survey link is disabled.
- Marketing notifications don't appear together
- The Neve FSE promotional message on the Themes screen must not appear if the user is already using Neve FSE.

### PR DESCRIPTION
**Pull request by cristian-ungureanu**
### Summary

This PR:
- disables the survey notice
- Every other necessary change is handled in [Themeisle SDK PR](https://github.com/Codeinwp/themeisle-sdk/pull/189)

### Will affect the visual aspect of the product
NO

### Test instructions
- Install this and make sure the survey is not visible anymore.
- Please follow the indications from [Themeisle SDK PR](https://github.com/Codeinwp/themeisle-sdk/pull/189)

Closes #69.

### CODE REVIEW

**Review by HardeepAsrani — APPROVED** [review]

File: inc/Admin.php [hunk 1]
```diff
@@ -13,6 +13,15 @@
...
  */
 class Admin {
+
+	/**
+	 * Property to suspend the survey.
+	 * Change it to true to enable it.
+	 *
+	 * @var bool
+	 */
+	private $suspend_survey = false;
```
Comment (HardeepAsrani) [inline inc/Admin.php:23]: Sorry for missing this initially, but shouldn't it be the other way around not to display the notice?

Comment (cristian-ungureanu) [reply inc/Admin.php]: Sorry for missing it, I've enabled it to test the behavior of other notices and forgot it like this.
